### ISSUE TITLE
Incorporate MATC_Projects in the UI

### ISSUE THREAD

**Issue by 50417** [CSE3311-Team8/SampleSLProject#5]
The goal is to come up with UI design to incorporate MATC_Projects table.
An idea could be to have a drop down list (GitHub, Matlab central and All) and certain attributes could be greyed out with respective selection.

**Comment by carlos-uresti** [comment]
Latest update on my branch incorporates MATC  projects into the search options. There is now a drop down menu where you can select GitHub, MATCH or All.  I was able to pull relevant information from both projects and use the existing table structure. The GitHub results are displayed first since there is relatively less of them, then MATC  projects follow, this is when using All to search. Once information is in a hosted database, we can probably query and mix the results better. Every search-result item is now its own table with better styling. Buttons have been updated with a popper and bootstrap library and look/feel much better. A simple "searching..." is displayed between searches to give the feel of a loading screen. We can update the isLoading feature with some kind of loading graphic instead if desired.  The filter page captures values from the inputs available but does not search yet. Right now the app is moving bulk data from json files, once we have web hosted data I'll restructure information requests to use a query format for specific data only.
